application_name: TAG

company: MarcelyK

version: 0.1.0

box_width: 170

box_height: 60

horizontal_spacing: 80

vertical_spacing: 80

node_dimensions:
  External:
    width: 160
    height: 80

  Integration:
    width: 180
    height: 80

  Transactional:
    width: 200
    height: 80

  Master Data:
    width: 180
    height: 80

  Unknown:
    width: 160
    height: 80

connection_labels:
  node_classification:
    attribute: category

    priority:
      - value: External
        code: SB
      - value: Integration
        code: TC
      - value: Transactional
        code: DWH
      - value: Master Data
        code: API

  sequence:
    width: 3
    start: 1
